#!/usr/bin/env bash
#  ╦ ╦╦╔╦╗╔═╗  ╔╗ ╔═╗╦═╗
#  ╠═╣║ ║║║╣   ╠╩╗╠═╣╠╦╝
#  ╩ ╩╩═╩╝╚═╝  ╚═╝╩ ╩╩╚═
#	Simple script to hide/show polybar

function hide() {
	
case "${RICETHEME}" in
    karla)
        polybar-msg cmd hide | bspc config top_padding 2
        ;;
    *)
        echo "Error: Something fails dude.."
        ;;
esac
	
}

function unhide() {
	
case "${RICETHEME}" in
	karla)
		polybar-msg cmd show | bspc config top_padding 48
		;;
	*)
		echo "Error: Something fails dude.."
		;;
esac

}

case $1 in
	-h | --hide | hide)
		hide
		exit;;
	-u | --unhide | unhide)
		unhide
		exit;;
	*) # Invalid option
		echo "Error: Invalid option"
		exit;;
esac
